### ISSUE TITLE
HHIT vs DET use

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-registries#10]
Throughout the document HHIT and DET are used interchangeably. I do believe in a previous discussion it was decided that HHIT would be used when referring to the technology while DET for the use case.

Some help is requested to look at the DIME Roles (Section 4) to confirm the uses are correct in context. The section is especially tricky as the document dances around citing specific technical things and high level use-case items.

**Comment by evyncke** [comment]
Without any hat, I think that in all DRIP documents, DET should be used.

**Comment by boucadair** [comment]
> I do believe in a previous discussion it was decided that HHIT would be used when referring to the technology while DET for the use case.

ACK. That's appropriate for RID. 

However, and given that the registry is really specific to DRIP, I suggest we simplify the terminology and adopts DET. The same would apply for the auth I-D. Thanks.

**Comment by kc2rxo** [comment]
I agree. In both documents I will change to be DET instead of HHIT.

**Comment by kc2rxo** [comment]
fe6c1d6
