### ISSUE TITLE
DIME Abbreviation Fallback

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-registries#11]
In Section 4.4 it is discussed that if no abbreviation is known for a DIME that the hexadecimal is used instead.

Do we specify that this fall back is: 

1. a fixed length of 4-characters in hex
2. variable up to 4-characters in hex
3. nothing

**Comment by evyncke** [comment]
Without any hat, isn't the fixed-length 4-characters in *uppercase* be better ?

In the same section, are the authors sure that there is a bijection between country and CAA ? (i.e., no CAA covering two countries like Skeyes.be for LU and BE ? ;-))

**Comment by kc2rxo** [comment]
fe6c1d6
