### ISSUE TITLE
Considering having examples to illustrate the various concepts in the draft  (serial number, session, operator, RAA, HDA, manufacturer: inputs  and outputs)

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-registries#17]

**Comment by kc2rxo** [comment]
@boucadair 

Section 6 is the primary section for this. A review from you on this section would be helpful to gauge what is missing and what can be clarified.

**Comment by kc2rxo** [comment]
The section has gone under extensive changes so a re-review is needed with the latest content.
