### ISSUE TITLE
X.509 Certificate Management

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-registries#21]
This content should be coming from @rgmhtt at some point when ICAO work is more formalized.

**Comment by rgmhtt** [comment]
This is part of my request to ICAO that we develop a profile for DET X.509 certificates that fit into the IATF Certificate Profile.

**Comment by kc2rxo** [comment]
Bob has given me some text that is now in the -11 working copy.
