### ISSUE TITLE
OID Allocation

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-registries#23]
As cited in an Editor Note the current OID is a personal one from @rgmhtt.

We will need to allocate one for DRIP if we choose to support it.

**Comment by rgmhtt** [comment]
I am looking to the ICAO with their arc of 1.3.27 for this.  I will be presenting this request at their Trusted Framework Panel meeting the last week in March.  I am proposing two approaches:  1.3.27.uas(9).drip(1).endorsements(1) or leave off the uas level.

Stay tuned.

**Comment by kc2rxo** [comment]
@rgmhtt is this something we still need? I wonder due to it being tied to your TFP work it may be better suited to be in DKI. Thoughts?

**Comment by kc2rxo** [comment]
The current document version (-15) no longer has the OID listed. Closing this issue.
