### ISSUE TITLE
IANA Registry for RAA Ranges?

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-registries#26]
https://github.com/ietf-wg-drip/draft-ietf-drip-registries/blob/42cc8b509e3c24a5beab12b30a862ff7e7957d9d/registries.mkd?plain=1#L149

Should we have an IANA registry for this?

**Comment by kc2rxo** [comment]
I am unsure and will extend this question to the working group via list. 

I am sure that would make sense at least for RAAs. I am hesitant to enumerate all the values in say the ISO range as that is a lot (999 of them) and I include the logic for it in the draft.

I strongly do not want to have a IANA registry for the Manufacturer Code HDA mapping. I would rather just leave that as pseudo-code in the draft that can be implemented.

**Comment by kc2rxo** [comment]
I am hoping that by -15 we have a better idea on the INN table and then add IANA registry for this.

**Comment by kc2rxo** [comment]
See 07e806a760220b6d5603956d65bf24a200b65d1e

**Comment by kc2rxo** [comment]
Part of v15
