### ISSUE TITLE
ICAO-Related Normative text

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-registries#34]
from @evyncke 

> De : Tm-rid <[tm-rid-bounces@ietf.org <mailto:tm-rid-bounces@ietf.org](mailto:tm-rid-bounces@ietf.org%20%3cmailto:tm-rid-bounces@ietf.org)>> 
> De la part de Eric Vyncke
> (evyncke)
> Envoyé : mercredi 19 juillet 2023 09:01 À : [tm-rid@ietf.org](mailto:tm-rid@ietf.org) 
> <mailto:tm-rid@ietf.org> Objet : [Drip] Questions about 
> draft-ietf-drip-registries-12
> 
> I had a quick browse through draft-ietf-drip-registries-12, especially 
> section 8 about DNS. And with my AD hat and I know that this I-D is 
> still in development, I have three questions/issues:
> 1) unsure whether an IETF document can write normative SHOULD to 
> another SDO like ICAO. At the bare minimum, a Liaison Statement should 
> be issued to ICAO.

[Med] Right. We had the same discussion for RFC 9374. We need to follow the same approach here as well.

**Comment by kc2rxo** [comment]
See 8fa117029fff1cfdfd394ca308690e969296e38a
