### ISSUE TITLE
delegation of 3.0.0.1.0.0.2.ip6.arpa

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-registries#36]
from @evyncke:

> 3) should we start more discussion with IANA on how the delegation of 
> 3.0.0.1.0.0.2.ip6.arpa can be done? Or is it too early ?
> 

[Med] I understood from the last interim that it would be good to start that process. I let Jim confirm/infirm, though.

**Comment by kc2rxo** [comment]
There is now as of -12 a section dedicated to this in IANA Considerations.
