### ISSUE TITLE
DET Resource Record as a separate I-D?

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-registries#38]
from @evyncke 

section 8.1.1 the DET Resource Record should probably be done in 
> DNSOP (the I-D can keep the text for now but should probably be moved 
> to a DNSOP I-D later in the process)

**Comment by boucadair** [comment]
I think this content can stay in this I-D, but designated Experts can be pointed to this section when reviewing the DET RRtype request. No need to have a separate I-D, IMO.

**Comment by kc2rxo** [comment]
The content is now moved to an Appendix. I agree with @boucadair that this can stay in as a reference.
